# Generated by Django 5.2 on 2025-04-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nid_num',
            field=models.IntegerField(default=0),
        ),
    ]
